# Generated by Django 4.1.2 on 2022-12-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_usermatch_diffculty_alter_usermatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermatch',
            name='diffculty',
            field=models.CharField(choices=[('normal', 'normal'), ('medium', 'medium'), ('hard', 'hard')], default='normal', max_length=6),
        ),
    ]
